### ISSUE TITLE
Named arguments should not be translated

### ISSUE THREAD

**Issue by bguan** [codegrue/auto-translate-json#1]
I am using flutter plugin Easy Localization which supports named argument. 

In my en-US.json, I have an entry:
`"test": "Zip code {zip} is in {city}, {state}.",`

After running 'Auto Translate JSON' using the extension in VSCode, it got translated in es.json as:
`"test": "El código postal {zip} está en {ciudad}, {estado}.",`

Named arguments should never be translated i.e. `{city}` should remain as is rather than becoming `{ciudad}`, and `{state}` shouldn't become `{estado}`.

**Comment by codegrue** [comment]
Good catch. It's passing the entire string over to Google as is so I will have to figure out how to segregate that data. Will add that in tonight.

**Comment by codegrue** [comment]
I published the fix just now. Version 1.0.6. Please give it a go. Thanks!
