### ISSUE TITLE
Json Format modified during translating process

### ISSUE THREAD

**Issue by therealcorwin** [codegrue/auto-translate-json#10]
Hi @codegrue :)

Thx for your vscode addon !

I have a question for you. I think, have i a bug during a translation. 

First, under vscode have i this error : 
AutoTranslateJSON: text.match is not a function
AutoTranslateJSON: Cannot read property 'match' of null

i tried to find more information about this, but unsuccessful.

Second things,
Between the original et translated files some differences appear. For Exemple  : 

Original File : 

> {
          "key": "s2",
          "title": "Let the Show Begin",
          "description": "Summons water droplets resembling musical notes that form a Melody Loop, dealing Hydro DMG to surrounding enemies and afflicting them with the Wet status.",
          "abilities": [
            {
              "name": "Melody Loop",
              "description": null,
              "descriptions": [
                "Barbara's Normal Attacks heal all party members and nearby allied characters for a certain amount of HP, which scales with Barbara's Max HP.",
                "Her Charged Attack generates 4 times the amount of healing.",
                "Regenerates a certain amount of the current character’s HP at regular intervals.",
                "Applies the Wet status to the character and enemies who come in contact with them."
              ]
            }
          ]
        }

Translated File : 
 

>  **"1": {**
          "key": "s2",
          "title": "C'est parti pour le show ♪",
          "description": "Invoque des gouttelettes d'eau ressemblant à des notes de musique qui forment une boucle de mélodie, infligeant des DMG Hydro aux ennemis environnants et leur attribuant le statut Trempé.",
          "abilities": {
            **"0":** {
              "name": "Boucle de mélodie",
              "description": null,
              "descriptions": {
                **"0":** "Les attaques normales de Barbara soignent tous les membres du groupe et les personnages alliés à proximité pour une certaine quantité de HP, qui évolue avec les HP Max de Barbara.",
                **"1":** "L'effet des soins est multiplié par 4 avec les attaques chargées.",
                **"2":** "Régénère à intervalles réguliers une certaine quantité de PV du personnage actuel .",
                **"3":** "Barbara trempe les personnages et les ennemis avec qui elle entre en contact."
              }
            }
          }
        }
In bold the famous differences

In this archive the original and translated file : 
[i18n.zip](https://github.com/codegrue/auto-translate-json/files/6564902/i18n.zip)

If you have some question for this issue, don't hesitate 👍 

Best regards,
Therealcorwin.

**Comment by coup** [comment]
I face the same issue and due to this i am not able to use the translated fiels intead of array it replaces index and the curly braces. Do we have any workaround for this ?

**Comment by marcguillemdev** [comment]
Same here, i tried to translate a JSON with a bunch of arrays and i received objects instead.
For example: 

> ORIGINAL
```
imagesWithDescription: [
        "Operario usando una sierra eléctrica para cortar metal",
        "Operario realizando una soldadura TIG"
      ]

```
> RECEIVED

```
"imagesWithDescription": {
        "0": "Operator using an electric saw to cut metal",
        "0": "Operator performing a TIG welding"
      }
```

In my case i'm using AWS.

Thanks for the extension!

**Comment by topce** [comment]
Hello

this is fixed  and will be available in  next release.
so I will close it .

@coup, @therealcorwin, @marcguillemdev, 
If you have time you can build extension and test it ,
or test it when @codegrue  deploy new version of extension.

Thank you for your help!
