### ISSUE TITLE
Arrays are not preserved

### ISSUE THREAD

**Issue by davidonet** [codegrue/auto-translate-json#12]
```json
"options": [
        {
          "value": "M",
          "text": "Male"
        },
        {
          "value": "F",
          "text": "Female"
        },
        {
          "value": "U",
          "text": "Prefer not say"
        }
      ]
```
became
```json
 "options": {
        "0": {
          "value": "M",
          "text": "Homme"
        },
        "1": {
          "value": "F",
          "text": "Femme"
        },
        "2": {
          "value": "U",
          "text": "Je préfère ne pas préciser"
        }
      }
```
and thus break the underlying code.

**Comment by codegrue** [comment]
I'm using the typescript JSON.stringify to do the encoding so I have no control over how it does this. The solution would require switching to another JSON package possibly. Are you sure this breaks the code? Having position number in the array should not affect how you are accessing the array...

**Comment by codegrue** [comment]
Okay I see, it actually removed the array. I'm going to have to investigate further.
