### ISSUE TITLE
Add support for using Microsoft/Azure Translate API 

### ISSUE THREAD

**Issue by SamHasler** [codegrue/auto-translate-json#13]
please consider adding support for the Microsoft / Azure translator API

https://azure.microsoft.com/en-us/services/cognitive-services/translator/#overview

Pricing (It has a 2M character per month limit on it's Free tier):
https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator/

Language Support:
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support

**Comment by SamHasler** [comment]
@topce Thank you!! You've made my day.

**Comment by topce** [comment]
@SamHasler my pleasure ;-)
please test if it works with Azure
I just test AWS

**Comment by codegrue** [comment]
1.1.0 is published

**Comment by topce** [comment]
Thank you!

**Comment by SamHasler** [comment]
AWS and Azure support (some) country codes, whilst Google doesn't. I've put more detail in #9 since this is closed and the filename format will also need to be taken into consideration.
