### ISSUE TITLE
Support for subfolders

### ISSUE THREAD

**Issue by gajo357** [codegrue/auto-translate-json#15]
Hi 

Is there any chance to implement the support for the structure

- locales
  - en
    - translation.json
  - es
    - translation.json
...

I can help to implement it?

**Comment by codegrue** [comment]
I've looked at this before and the way the included components work I didn't think it was possible. However, I am happy to receive a pull request if you solve it and the original scenario still functions.

**Comment by gajo357** [comment]
My thinking was to have a new entry in settings, where you choose if your structure is "file" or "folder".
Then the tool does not have to be too smart.
I will take a look at it...

**Comment by codegrue** [comment]
Looks good at a glance. Did you test it still works with a flat structure?

**Comment by codegrue** [comment]
Apologies I missed this PR and now it conflicts. If you are able to update it I will pull it in. Thanks!

**Comment by gajo357** [comment]
For the default path, I didn't make any changes. I should work as before.
Just saw that you merged it, is this now considered closed?
