### ISSUE TITLE
Plugin does nothing

### ISSUE THREAD

**Issue by ghost** [codegrue/auto-translate-json#2]
Hey, so I set up everything. Followed all the instructions. But whenever I click auto translate it just does nothing. No error. No popup. Can't figure out what the issue is.

**Comment by codegrue** [comment]
Can you do Discord screen share so I can observe the steps? PM please at CodeGrue#3994

**Comment by oraharon** [comment]
Hi Codegrue, I installed your plugin today and I face the same issue.

**Comment by codegrue** [comment]
You both have a valid Google Translate account? Do you see any errors in the VScode terminal?

**Comment by ghost** [comment]
Yeah had no issues getting the API key. 

Nope. No errors anywhere.

**Comment by codegrue** [comment]
Do you get the prompts at the top to select options?

**Comment by codegrue** [comment]
The only thing between API Key check and prompts is getting a path to the filesystem. What OS are you guys on? I have not tested this on Windows...

**Comment by ghost** [comment]
Ah that's definitely the issue then. I'm on Windows.

**Comment by codegrue** [comment]
Might be an authorization issue to write to files. I will release a new version shortly with more error feedback to help find the cause. I can also set up on Windows to test if needed.

**Comment by codegrue** [comment]
1.0.7 is published. Please try and report back what you see for messages.

**Comment by ghost** [comment]
AutoTranslateJSON: Opening FilesENOENT: no such file or directory, scandir '/c:/Users/Fawad/Documents/My Projects/Unit Converter/Code/konvertr/assets/i18n'

**Comment by codegrue** [comment]
Is that a valid path and the one where all the JSON files exist?

**Comment by ghost** [comment]
The leading / before c:/ is the only issue. Rest is valid.

**Comment by codegrue** [comment]
Prefect that helps. I found the issue and published the fix in 1.0.8. Please give it a shot and let me know. Thanks!

**Comment by ghost** [comment]
Worked perfectly. Thanks for all your help!
