### ISSUE TITLE
Google translate gives error this.googleTranslate.getLanguages is not a function

### ISSUE THREAD

**Issue by freakness** [codegrue/auto-translate-json#23]
![image](https://user-images.githubusercontent.com/11801732/149508454-8656d389-2b8a-4edf-a8f9-b33ab3bc89cd.png)

See attached image. 

Steps to reproduce:

1. CTRL/CMD+SHIFT+P 
2. Search for auto translate + ENTER
3. Error pops

Right clicking on a en.json file does not do anything.

**Comment by Stefano191** [comment]
Same error, the whole extension stopped working aswell. Older versions have same problem.

**Comment by codegrue** [comment]
I pushed out a new version. Google broke api key access so it no longer works.  I Attempted to downgrade to get it working again.

**Comment by Stefano191** [comment]
> I pushed out a new version. Google broke api key access so it no longer works. I Attempted to downgrade to get it working again.

I can confirm that it is working again, thanks for the fast `temporary´ fix.

**Comment by topce** [comment]
fix by @codegrue
so I close this one as well
