### ISSUE TITLE
Azure translation returns json structure

### ISSUE THREAD

**Issue by fmfikjellh** [codegrue/auto-translate-json#25]
Hi,

I'm trying to translate from en.json file to fr.json. I'm using the Azure translation service. It seems that Azure translation is not inserting only the translated text into the target language file, but it inserts the entire response json structure.

Example:
Source en.json
`{
  "info": "Click here for more info"
}`
Result:
`{
  "info": [
    {
      "translations": [
        {
          "text": "Cliquez ici pour plus d’informations",
          "to": "fr"
        }
      ]
    }
  ]
}`

The attached zip contains the source and result files:
[translation_sample.zip](https://github.com/codegrue/auto-translate-json/files/7956632/translation_sample.zip)

**Comment by codegrue** [comment]
@topce thoughts on this one?

**Comment by topce** [comment]
Hi @eckjellh  thank you for testing !
Unfortunately do   not have azure account to test ;-(
@codegrue 
According files that @eckjellh  send us
and documentation https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translator?tabs=nodejs
I think that #26  PR will fix it  (need to be tested).
When you have a time can you please deploy new version
on marketplace?

**Comment by codegrue** [comment]
Love testing in production. Deploying now...

**Comment by codegrue** [comment]
Fix deployed in 1.1.3

**Comment by jproefrock** [comment]
I have 1.1.3 installed and am seeing the same results as above still.  Do I need to change a setting somewhere?  

Thanks in advance!

**Comment by codegrue** [comment]
I need to test this again as reports are it's not working. Will do so shortly.

**Comment by gingemonster** [comment]
1.1.4 still doing the same thing on azure

**Comment by AppElent** [comment]
This is still the case!
it returns custom fields like this:
{
  "pages": {
    "login": {
      "title": [
        {
          "translations": [
            {
              "text": "Melden Sie sich bei Ihrem Konto an",
              "to": "de"
            }
          ]
        }
      ],

the translations{text, to} is custom and only the text should be displayed.
The original is like this:
{
    "pages": {
        "login": {
            "title": "Sign in to your account",
            "signin": "Sign in",
please fix, because this is pretty blocking :)

**Comment by amh521** [comment]
Also still having this problem with Azure translations. Makes the plugin useless using Azure.
