### ISSUE TITLE
AWS access when MFA is enabled on the aws account

### ISSUE THREAD

**Issue by sacag** [codegrue/auto-translate-json#37]
Getting this exception. I have the correct access key is and secret setup in the extension settings in vscode, but getting the below exception. Thoughts?
**UnrecognizedClientException: The security token included in the request is invalid.**

**Comment by topce** [comment]
Hello  @sacag ,
we do not support MFA
so better to create another user that does not use MFA and has
attached policy TranslateFullAccess
and use this user for automatic translation
