### ISSUE TITLE
Automate this via a build step or github action?

### ISSUE THREAD

**Issue by sachin-tive** [codegrue/auto-translate-json#38]
Can this be automated somehow via github actions or one of the build steps in my build process? I understand not the vs code extension itself but the logic behind it to translate

**Comment by topce** [comment]
Good question.
Yes indeed we break it on ui vscode extension and npm library : 
https://github.com/topce/auto-translate-json-library
so indeed you can use library if you want 
https://www.npmjs.com/package/auto-translate-json-library
