### ISSUE TITLE
how to specify own dictionary?

### ISSUE THREAD

**Issue by githubbla** [codegrue/auto-translate-json#39]
the google api always assume that "table" it's like spreadsheet, but more frequently it's desk.

**Comment by topce** [comment]
@githubbla  Thank you for feedback!
Currently not implemented 
maybe it could be done with glossary for example for google : 
https://cloud.google.com/translate/docs/advanced/glossary#operation_status
You can try to use OpenAI maybe they do better translation context guessing

**Comment by topce** [comment]
too complicate to add glossary support for different providers 
try OpenAI maybe for this provider we can add glossary or translation context
