### ISSUE TITLE
ignore words feature? or how to?

### ISSUE THREAD

**Issue by githubbla** [codegrue/auto-translate-json#40]
Sometimes, you have variable and replacement inside text.
like 	

"faq.4.title": "(ticketsicon) Ticket Shop",
"dialog.low.balance.special.offer.text": "Get {{offer}} coins for {{price}}",

(ticketsicon) it's will be replaced by css things.
{{offer}} to variable...

when translate {{offer}} is always OK.
but (ticketicons) it's translated on some languages...

how possible to handle it?

**Comment by topce** [comment]
Currently it is not possible there is parameters 
startDelimiter and endDelimiter that are string  so you can set either to ignore 
( ) or {{  }} but not both 
if we generalize those parameters to be array of stings then it could be possible to ignore 
multiple values !

**Comment by topce** [comment]
I checked and it was too complicate to do it ,
so I close it
