### ISSUE TITLE
transalate only some key:value

### ISSUE THREAD

**Issue by CaosFR** [codegrue/auto-translate-json#41]
Hi and thanks for your extension.

Does it a way to transalate only value wich match some key instead of the whole file ?

Thanks

**Comment by codegrue** [comment]
What are your thoughts on how to indicate which would be excluded?

**Comment by topce** [comment]
You can select to translate just new translations,
also to remove translations that are not in source file.

**Comment by topce** [comment]
> What are your thoughts on how to indicate which would be excluded?
Not sure what @CaosFR had on mind.
Maybe to use prefix to ignore some keys
@codegrue  maybe if you have time to deploy latest version to vs code extension

**Comment by codegrue** [comment]
Update version published. 1.2.0

**Comment by topce** [comment]
@codegrue  
Thank you !
Maybe to add new parameter ignoreKeyPrefix
and to ignore translation that has key that starts with  ignoreKeyPrefix
if ignoreKeyPrefix is empty do nothing.
it could also help to resolve 
https://github.com/codegrue/auto-translate-json/issues/9 point 3 ignoreKeyPrefix = @ 
What do you think ?

**Comment by codegrue** [comment]
I like this idea if you are willing to implement it.

**Comment by topce** [comment]
Done : https://github.com/codegrue/auto-translate-json/commit/7215cb8cf88ba38e0dd03558aa3005147571ad84
Maybe when you have time to publish there is also Open AI support in new version
