### ISSUE TITLE
result.replace is not a function

### ISSUE THREAD

**Issue by phoyer** [codegrue/auto-translate-json#43]
When trying to translate using Azure, after entering the key and region germanywestcentral, I will always get the error message:

**AutoTranslateJSON: result.replace is not a function**

This happens on different computers and under Windows as well as Linux. Any ideas?

I can also provide the key as private message if required...

Thank you!

Peter

**Comment by ncosgray** [comment]
I've noticed this error too. It only seems to affect strings that include named argument delimiters.

**Comment by topce** [comment]
@ncosgray @phoyer  Can you post some details so we can try to reproduce issue 
@codegrue maybe  to publish latest version to vs code extensions

**Comment by codegrue** [comment]
Update version published. 1.2.0

**Comment by topce** [comment]
@codegrue thank you for update !
@phoyer and @ncosgray 
Thank you for reporting error !

Can you please test with latest version is it working better? 

If you still have problem:
Unfortunately do not have azure account to test 
We use similar code for azure translation like in Microsoft documentation 
https://learn.microsoft.com/en-us/azure/cognitive-services/Translator/quickstart-translator-rest-api?tabs=nodejs
code is in 
https://github.com/topce/auto-translate-json-library
```
public static replaceArgumentsWithNumbers(
    args: RegExpMatchArray | null,
    result: string
  ) {
    if (args) {
      let i = 0;
      for (let arg of args) {
        result = result.replace(
          Util._startDelimiter + i + Util._endDelimiter,
          arg
        );
        i++;
      }
    }
    return result;
  }
```
probably problematic line is result.replace
it is called from azure.ts
```
async translateText(
    text: string,
    sourceLocale: string,
    targetLocale: string
  ): Promise<string> {
    let args;
    ({ args, text } = Util.replaceContextVariables(text));

    let result = '';

    const response = await axios({
      baseURL: this.endpoint,
      url: '/translate',
      method: 'post',
      headers: {
        'Ocp-Apim-Subscription-Key': this.subscriptionKey,
        'Ocp-Apim-Subscription-Region': this.subscriptionRegion,
        'Content-type': 'application/json',
        'X-ClientTraceId': uuidv4().toString()
      },
      params: {
        'api-version': '3.0',
        from: sourceLocale,
        to: [targetLocale]
      },
      data: [
        {
          text: text
        }
      ],
      responseType: 'json'
    });
    result = response.data[0].translations[0].text;

    result = Util.replaceArgumentsWithNumbers(args, result);

    return result;
  }
```
so probably response.data[0].translations[0].text is undefined 

Please fill free to create PR if you found what is problem.
https://github.com/topce/auto-translate-json-library
also can try to run example 
https://learn.microsoft.com/en-us/azure/cognitive-services/Translator/quickstart-translator-rest-api?tabs=nodejs#translate-text
to see if it works

**Comment by topce** [comment]
this should be fixed 
please test with latest version of extension
