### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by psarno** [codegrue/auto-translate-json#45]
I entered my OpenAI key, created a blank fr.json file, right-clicked my en.json file and ran the extension using the defaults.

![image](https://github.com/codegrue/auto-translate-json/assets/18640860/a38f6e4d-24a8-446e-b5df-26faa90039d1)

It immediately says it worked (which is clearly a sign it didn't) and the fr.json file is empty.

![image](https://github.com/codegrue/auto-translate-json/assets/18640860/29c3ed26-bef5-4ba0-8f7d-bc90252a9916)

**Comment by zackrspv** [comment]
Getting the same thing here, honestly. Not sure exactly what is causing it

**Comment by aligkts** [comment]
having same issue right now

**Comment by topce** [comment]
@zackrspv @aligkts @psarno  
Thank  you for reporting !
I will double check.
Do you use latest vs code or vs code insider ?

**Comment by topce** [comment]
@psarno why you close it 
is it working now for you?

**Comment by topce** [comment]
strange I just tested and for me and it woks ?
Can not reproduce it ,
do you see some errors in extension logs?

**Comment by topce** [comment]
@psarno 
can you provide minimal files that you want to translate so we can try to reproduce error

**Comment by topce** [comment]
@psarno  it takes some time until translation is done
