### ISSUE TITLE
Bengali translations do not work via extension

### ISSUE THREAD

**Issue by bubenkoff** [codegrue/auto-translate-json#46]
But they seem to work correctly when using the auto-translate-json-library directly.
The extension shows that translations are added, but nothing happens.
Also, no errors in the console, and no way to debug it seems.
CAn you please help?

**Comment by codegrue** [comment]
@bubenkoff which translator are you using?

@topce Any ideas?

**Comment by bubenkoff** [comment]
> @bubenkoff which translator are you using?
> 
> @topce Any ideas?

Google Translate

**Comment by topce** [comment]
Strange it is same code that is used actually library is extracted from extension. 
If it worked for library it should work for extension?
@bubenkoff do you have minimal case to reproduce?
What are filenames guess en.json an what is other for bengali translation? 
Unfortunately does not have google key to test .
Do you have some error in extension logs ?
Last time I test with AWS it was working, but did not test bengali translation.
Also check did you correctly set up extension parameters?

**Comment by topce** [comment]
> > @bubenkoff which translator are you using?
> > @topce Any ideas?
> 
> Google Translate

I will double check maybe ignorePrefix option that is added recently not working as expected

**Comment by bubenkoff** [comment]
Thanks, but where is the extension log actually?
Cannot find anything in the output nor problems.

**Comment by bubenkoff** [comment]
it's actually stopped working for all translations, not just Bengali

**Comment by topce** [comment]
@bubenkoff  maybe try to add ignorePrefix some dummy string @@@ 
and see if it works better 
I will doublecheck

**Comment by topce** [comment]
what version of vs code and extension you use ?
I will try for AWS

**Comment by topce** [comment]
and check in code 
sorry for inconvenience

**Comment by topce** [comment]
@bubenkoff  just tested with AWS latest version of vs code and latest version of extension it is working OK

**Comment by bubenkoff** [comment]
Auto Translate JSONv1.3.1
setting the prefix setting to some string didn't help

**Comment by topce** [comment]
Thank you @bubenkoff for feedback
Strange for me it is working with AWS ,
@codegrue I initialize ignorePrefix as empty string , 
but probably will not help because it was already default value 
`
"auto-translate-json.ignorePrefix": {
          "type": "string",
          "default": "",
          "markdownDescription": "Ignore prefix for translation key"
        }
`

**Comment by topce** [comment]
strange just tested on OpenAi and it also works for me.
Will try to test with empty files

**Comment by bubenkoff** [comment]
How do I enable debug logs to see what the extension actually does?

**Comment by topce** [comment]
@bubenkoff thank you for help.
I think  that I succeed to reproduce it 
 it look like our last version does not handle empty json file good 
 `
 {
  
}
 `
 does not translate anything
 but 
 `
 {
 "":""
 }
 `
 works 
 will try to fix tonight 
Thank you for reporting 
You can try to install previous  version of extension 
until we fix issue 
work around add some key to json file.

**Comment by bubenkoff** [comment]
but there are no empty json files involved at all.
All the files are not empty, just some values are when translations are
missing.
But you call to translate, it doesn't show the usual, separate,
per-language notifications in the VS code, about that it's done with
translating that language.
It seems it just really does nothing now.

**Comment by topce** [comment]
duplicate 
same like https://github.com/codegrue/auto-translate-json/issues/45
empty json files are not handled properly 
workaround add something in  
json file for example 
`
{
"":""
}
`

**Comment by topce** [comment]
@bubenkoff  
do you have files that you try to translate empty json files : {}
or empty file ""?
with empty JSON files   it look like does not work for me ?

**Comment by bubenkoff** [comment]
There are no empty files in my setup.

**Comment by topce** [comment]
@bubenkoff  strange for me it works with AWS and OpenAI
can you share minimal files that you want to translate so it we can try to reproduce ,
I do not have Google API key but @codegrue  can try to reproduce
what parameters you use ?
of course except google key .

**Comment by topce** [comment]
@codegrue  is it working for you when you google translate ?

**Comment by codegrue** [comment]
Had to switch over to Google Translate. Yes bn.json worked and populated with the translation.

"description": "Description", -> "description": "বর্ণনা",

BTW, I just created an empty "bn.json" file and it populated as expected.

**Comment by topce** [comment]
> Had to switch over to Google Translate. Yes bn.json worked and populated with the translation.
> 
> "description": "Description", -> "description": "বর্ণনা",
> 
> BTW, I just created an empty "bn.json" file and it populated as expected.

Thank you maybe to put some form with example files how to reproduce bug 
There are a lot of options, providers,
I use plugin in daily work for me it works 
It works on my PC ;-)
I check with AWS and OpenAI also worked as expected . 
We can not fix a bug if we can not reproduce it  ;-)

**Comment by bubenkoff** [comment]
I think the way forward is to have debug logging, can you please add debug
setting and also debug logging?

**Comment by topce** [comment]
@bubenkoff  indeed we need to improve there 
but maybe you can check example of @codegrue 
en.json
and 
bn.json
is it working for you?
there are a lot parameters some dynamic some , from settings .

**Comment by bubenkoff** [comment]
the empty file also didn't work - it's the same behavior

**Comment by bubenkoff** [comment]
cloned the extension and running it locally - the issue seems to be in the https://github.com/topce/auto-translate-json-library not in the extension itself, there seems to be some issue introduced with the most recent version.

**Comment by bubenkoff** [comment]
@topce sorry, it's very strange but now it works again!

**Comment by bubenkoff** [comment]
I don't really understand, maybe it's some timeout in API calls that led to that behavior in the past?

**Comment by topce** [comment]
@bubenkoff  what version of vs code and extension you use?
I use latest for me works .
vs code 
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z (1 wk ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

@codegrue  try with Google it works for him as well.
Maybe some parameter is not set up correctly.
You can in vs code go to help / toggle developer tools 
and perform auto translation 
check if you have some error in console 
good luck!

**Comment by bubenkoff** [comment]
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0

in console no errors now, but it's working now so that's correct

**Comment by topce** [comment]
@bubenkoff  
OK thank you for you help!
Glad that is finally working ;-)

**Comment by topce** [comment]
@bubenkoff  out of curiosity : 
What was problem ?
Did not use latest version of vs code ?

**Comment by bubenkoff** [comment]
Really, no idea! Thanks for the help anyways!
