### ISSUE TITLE
Issue with Deepl translation

### ISSUE THREAD

**Issue by Sylvesterx1** [codegrue/auto-translate-json#48]
Hi, 
this is my input struture json:
{
  "accountLayout": {
    "myProfile": "My profile",
    "myAddressBook": "My address book",
    "vouchers": "Vouchers",
    "myOrders": "My orders",
    "myWishlist": "My wishlist",
    "comparedList": "Compared list"
  },
  "trackOrder": {
    "estimatedDelivery": "Estimated delivery",
    "estimated": "Estimated",
    "enterCode": "Enter the track code of your order",
    "trackOrder": "Track Your Order",
    "orderStatus": "Status of the Order",
    "haveAnOrder": "Have an order? Want to know where your order is now?",
    "knowProgress": "Know the progress of your product delivery."
  },
  "addressPopup": {
    "country": "Country",
    "order": "Order",
    "state": "State",
    "email": "Email",
    "name": "Name",
    "address": "Address",
    "city": "City",
    "zipCode": "Zip code",
    "isRequired": "{type} is required",
    "phone": "Phone",
    "cancel": "Cancel",
    "update": "Update",
    "thisAddress": "{type} this address",
    "saving": "Saving",
    "save": "Save",
    "message": "Message",
    "addressPlaceholder": "Street address or P.O. Box",
    "address2Placeholder": "Apt, suite, unit, building, floor, etc.",
    "subject": "Subject"
  },
........
.....

and I get output:
{
  "accountLayout": {},
  "trackOrder": {},
  "addressPopup": {},
...
....
...
...
...
}

**Comment by topce** [comment]
@Sylvesterx1  thanks for reporting 
 Did you put DeepL key in settings ?
When you help/toggle developer tools in vs code do you see errors in console ?
Unfortunately does not have DeepL key to test it ...
