### ISSUE TITLE
Wrong endpoint for DeepL free API

### ISSUE THREAD

**Issue by jabguru** [codegrue/auto-translate-json#52]
I tried using the DeepL free api, i got error in the log

Error: getaddrinfo ENOTFOUND api.free.deepl.com at Function.AxiosError.from

The endpoint being used is "api.free.deepl.com"

but on the website the endpoint is "api-free.deepl.com"

**Comment by topce** [comment]
Thank you for reporting issue  @jabguru!  
Error was in library https://github.com/topce/auto-translate-json-library
I fix it in this commit 
https://github.com/topce/auto-translate-json-library/commit/2aaea6e29888f5b1fce74ce7e63dc0d906a06a3a 
@codegrue  if you have time can you please publish extension 1.3.3?
@jabguru if you are in harry 
you can build vs code extension yourself 

## Build Steps

- npm install
- npm i  -g @vscode/vsce
- vsce package

and then install vsix file manually 

@jabguru  
Did not test with DeepL , so if there is more error please feel free to open new issue 
or even better PR if you can fix it .

**Comment by jabguru** [comment]
@topce @codegrue  I get this when i  did "vsce package"

 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/out/extension.js

**Comment by topce** [comment]
@jabguru   strange for me it works 
however it takes some time to build 
I use node v16.18.1

**Comment by topce** [comment]
@jabguru otherwise you can try to use library https://github.com/topce/auto-translate-json-library
directly if it is easier for you to troubleshoot problems

**Comment by jabguru** [comment]
@topce i don't think i'll be able to use the library, I need it in vscode.
How long before the extension is updated in the marketplace?

**Comment by jabguru** [comment]
@topce and where is extension/out/extension.js supposed to be located?

**Comment by codegrue** [comment]
I'll update it today in the marketplace

**Comment by topce** [comment]
@jabguru 
You need first to compile 
npm run compile 
and then execute 
vsce package

out folder should be in project root next to src folder

**Comment by codegrue** [comment]
Published 1.3.3. Please test.

**Comment by jabguru** [comment]
@codegrue still not working, another error this time.

[Extension Host] TypeError: Cannot read properties of undefined (reading '1') at DeepLTranslate.<anonymous> in workbench-desktop.main.js:131 and workbench-desktop.main.js:627

For OpenAI I get error 
ERR [Extension Host] Error: Request failed with status code 429 in same place
workbench-desktop.main.js:131 and workbench-desktop.main.js:627
