### ISSUE TITLE
Cannot get this to work (using DeepL API Free)

### ISSUE THREAD

**Issue by codeflorist** [codegrue/auto-translate-json#59]
This look really handy. Many thanks for creating this!

Unfortunately i cannot seem to get it to work.

I have a `DeepL API Free` account and entered the API key unter extension setting `Deep LFree Secret Key`.

Then i have two files in a folder:

`en.json` with the following content:
```json
{
	"monday": "Monday"
}
```

`de.json` with the following content:
```json
{}
```

When i right-click on `en.json` and choose `Auto Translate JSON` from the context-menu, then choose the default on the two following questions, an info-message is immediately displayed saying: `AutoTranslateJSON: Translations have been added to the file`. But `de.json` is still an empty object and no translations have taken place.

**Comment by emvaized** [comment]
I have the same problem, but for me only the keys are added, and value for each key is just an empty string

Errors in developer console: 
<img width="845" alt="Errors in console" src="https://github.com/user-attachments/assets/6b882128-9db5-4e35-b2a4-03b23800502c">

**Comment by topce** [comment]
@codeflorist  and @emvaized  

Thank you for reporting issue! 
It should be fixed 
with latest release.
You  can easy  build local extension and test with vsix file
@codegrue  when you have time maybe to publish extension
