### ISSUE TITLE
Translate to en-GB fails?

### ISSUE THREAD

**Issue by mike-albrecht** [codegrue/auto-translate-json#6]
Awesome plugin, thanks for writing. Just one issue I've experienced: trying to translate from `en.json`, (American) English, to `en-GB.json`, British English, seems to fail. Message: "AutoTranslateJSON: en-GB is not supported. Skipping." It _does_ work for other locale-specific languages like `zh-TW.json`, and `en-GB` does appear to be the correct language code according to [Google's API docs](https://developers.google.com/admin-sdk/directory/v1/languages). I've also tried `en-UK`, `en-BR` and for good measure.

**Comment by codegrue** [comment]
That's because I'm trying to standardize on one form of English... kidding! I'll take a look at it this week.

**Comment by mike-albrecht** [comment]
Ha, a reasonable goal! Appreciate your looking at it, cheers!

**Comment by codegrue** [comment]
Dug in. Looks like it's not actually supported by Google:

https://cloud.google.com/translate/docs/languages

**Comment by mike-albrecht** [comment]
Interesting. Thanks all the same for checking.
