### ISSUE TITLE
Proposal for additional settings/features

### ISSUE THREAD

**Issue by mk-dev-1** [codegrue/auto-translate-json#9]
Hi there,

the plugin is already very helpful, however I would like to propose the following additional features:

### 1. Allow for input file name customization
Currently the plugin is looking for `en.json` only. It would be great to customize this as my files have a `intl_` in front of it.

### 2. Allow for input file extension customization
Currently the plugin is looking for `json` only. It would be great to customize this as my files are ending in `arb`, which is essentially a json file.

### 3. Add filter options
Currently the plugin is looking for translating each and every string, but I would like to be able to define filters so that some strings to not get translated. Particularly, some of my strings look like this `"@testString": {...}`. I would like to filter out everything starting with `@`.

Do you think there is a chance to get this implemented?

**Comment by SamHasler** [comment]
Regarding point 1. We use filenames with country codes in them. 
e.g.:
```
en-GB.json
en-US.json
fr-FR.json
fr-CA.json
```

could either the filename pattern be somehow deduced from the current filename, or it be made configurable in some way. I would also expect to have to change the default locale to en-GB so it knows which english file to use, so perhaps that's all that it needs to switch to a different pattern?


Google doesn't support country codes
https://cloud.google.com/translate/docs/languages
(see also #6)
 
but the extension now also supports AWS and Azure and they do (e.g. both support fr-CA, but the call fr-FR just "fr"
https://docs.aws.amazon.com/translate/latest/dg/what-is.html#language-pairs
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support

So we will probably need to maintain a list of what languages each service supports (unless there's some way to query for it?) and handle mapping filenames to the most appropriate language code. 

For en-GB to en-US (or the reverse) it would be nice if it just copies the original file without translating, but if that was the only one I had to do by hand it wouldn't be ok.

---
Just in case anyone else is searching for it. If the extension doesn't understand your filename format you will see this error:
```
[Window Title]
Visual Studio Code

[Content]
Command 'Auto Translate JSON' resulted in an error (Cannot read property 'fsPath' of undefined)

[OK]
```
![image](https://user-images.githubusercontent.com/54277/149125098-6769e768-df6c-481e-89ca-ca492ead6f74.png)

**Comment by topce** [comment]
3.  is done could use new option ignorePrefix 
 other do not plan to do
